EventStore/EventStore.JVM

src/main/java/eventstore/j/examples/EventDataBuilderExample.java
There was some confusion from a customer about where event type was specified - this should clear it up a bit.
=> Make event type more explicit in examples

src/main/scala/eventstore/tcp/ConnectionActor.scala
When reconnecting, the connect itself may succeed, but retrying the subscribeTo operation
may timeout. This happens for example when EventStore is in the process of restarting. If
we wouldn't make the scheduleOnce call and subscribeTo indeed times out, we will never be
informed about it and consequently can never recover from it.
=> Add operation timeout when reconnecting

src/main/scala/eventstore/tcp/ConnectionActor.scala
- fix unhandled for `ClientIdentified`.
- rename msg to m to suppress shadow warning.
=> tcp: fix warning wrt. client identified msg

.travis.yml, src/test/resources/application.conf, src/test/scala/eventstore/ReadAllEventsForwardITest.scala, src/test/scala/eventstore/ScavengeITest.scala, src/test/scala/eventstore/SubscribeToAllCatchingUpITest.scala, src/test/scala/eventstore/SubscribeToAllITest.scala, src/test/scala/eventstore/TestConnection.scala, src/test/scala/eventstore/j/EsConnectionITest.scala, src/test/scala/eventstore/tcp/ConnectionActorSpec.scala
- define travis matrix such that we
run normal tests on 2.11.x & 2.12.x,
and only run integration tests on
2.12.x.
- add docker setup on travis such that
it:test can be run.
- fix flaky tests that either were subject
to race conditions or failing due to
reading es system streams when expecting
something else.
- add akka time factor setting to test config
in order to tweak CI.
=> ci: add es in docker to travis

src/main/scala/eventstore/EventStoreExtension.scala
- make extension lazy in order to avoid having two
instances of `ConnectionActor` running.
=> extension: make connection lazy

src/main/java/eventstore/j/EsConnection.java, src/main/scala/eventstore/AllStreamsSourceStage.scala, src/main/scala/eventstore/EsConnection.scala, src/main/scala/eventstore/SourceStageLogic.scala, src/main/scala/eventstore/StreamSourceStage.scala, src/main/scala/eventstore/j/EsConnectionImpl.scala, src/test/scala/eventstore/AllStreamsSourceITest.scala, src/test/scala/eventstore/AllStreamsSourceSpec.scala, src/test/scala/eventstore/StreamSourceITest.scala, src/test/scala/eventstore/StreamSourceSpec.scala, src/test/scala/eventstore/TestConnection.scala, src/test/scala/eventstore/j/EsConnectionITest.scala, src/test/scala/eventstore/util/SourceSpec.scala
- add `StreamSource` and `AllStreamsSource` graph stages
that replace deprecated `ActorPublisher` implementations
`StreamPublisher` and `AllStreamsPublisher`.
Closes #99
Co-authored-by: bardurdam <bardurdam@gmail.com>
=> streams: graph stage

src/main/scala/eventstore/StreamSourceStage.scala, src/test/scala/eventstore/StreamSourceSpec.scala
- change `StreamSourceStage` to use `event.record.number` such that event
numbers are correctly for resolved events.
=> streams: fix source stage wrt. event number

src/main/scala/eventstore/AllStreamsSourceStage.scala, src/main/scala/eventstore/SourceStageLogic.scala, src/main/scala/eventstore/StreamSourceStage.scala, src/test/scala/eventstore/AllStreamsSourceSpec.scala, src/test/scala/eventstore/StreamSourceSpec.scala
refactor `SourceStageLogic`s internal implementation such that it is easier to reason about.
- the implementation does not keep track of next position in order to simplify implementation. This means that the last read event may be read again in some cases, but in turn, fewer events are re-read overall because it keeps track of the last enqueued event instead of the last pushed event
improve test coverage for:
- unexpected resubscriptions during catching up and subscribed
- temporarily unsubscribing when buffer is full
- pausing reading when buffer is full
=> refactor SourceStageLogic such that it is easier to reason about

src/main/scala/eventstore/StreamSubscriptionActor.scala, src/test/scala/eventstore/StreamSubscriptionActorSpec.scala
- update catchup-to eventnumber when being resubscribed by ES while
catching up
- add test that proves fix
- this issue is not present in `SubscriptionActor`
=> fix StreamSubscriptionActor when being resubscribed while catching up

.travis.yml, README.md, build.sbt, project/build.properties, src/main/scala/eventstore/SourceStageLogic.scala, src/test/scala/eventstore/AllStreamsSourceSpec.scala, src/test/scala/eventstore/StreamSourceSpec.scala
- change `SourceStageLogic` to ignore incoming
events while unsubscribed instead of being
unhandled, resulting in error log.
- change `SourceStageLogic` to fail stage with
`UnhandledException` when getting messages it
does not expect.
- bump dependencies in build and travis.
- fix travis to fixed version of ES 4.1.2 as ES 5.x
has changed protobuf protocol for scavenging.
- adjust readme.
=> misc: change stagelogic logging of errors

.travis.yml, README.md, src/main/protobuf/EventStoreMessages.proto, src/main/scala/eventstore/EsException.scala, src/main/scala/eventstore/Message.scala, src/main/scala/eventstore/SystemError.scala, src/main/scala/eventstore/operations/ScavengeDatabaseInspection.scala, src/main/scala/eventstore/tcp/EventStoreProtoFormats.scala, src/main/scala/eventstore/tcp/MarkerByte.scala, src/test/scala/eventstore/ScavengeITest.scala, src/test/scala/eventstore/operations/ScavengeDatabaseInspectionSpec.scala
- ESv5 has changed protobuf protocol for scavenging,
so this is a response to that.
- bump major version of client as this is a breaking
change.
- set travis to use ESv5.
- update the readme.
=> EventStore v5 protocol changes

src/main/scala/eventstore/operations/Operation.scala, src/main/scala/eventstore/operations/PersistentSubscriptionOperation.scala, src/main/scala/eventstore/operations/RetryableOperation.scala, src/main/scala/eventstore/operations/SimpleOperation.scala, src/main/scala/eventstore/operations/SubscriptionOperation.scala, src/main/scala/eventstore/tcp/ConnectionActor.scala, src/test/scala/eventstore/ContentTypeITest.scala, src/test/scala/eventstore/ScavengeITest.scala, src/test/scala/eventstore/operations/OperationSpec.scala, src/test/scala/eventstore/operations/PersistentSubscriptionOperationSpec.scala, src/test/scala/eventstore/operations/RetryableOperationSpec.scala, src/test/scala/eventstore/operations/SubscriptionOperationSpec.scala
- parameterize client of `Operation` such that it
not tied to a concrete implementation.
- adjust tests and code accordingly.
- fix `ScavengeITest` for failing tests
that happens when first test scavenge
not completes before second test runs.
=> operations: decouple actor client from operation

build.sbt, src/main/scala/eventstore/util/PasswordHashAlgorithm.scala
- replace `org.apache.commons.codec.binary.Base64`
usage with equivalent functionality from
`java.util.Base64`.
=> util:remove org.apache.commons.codec.binary.Base64

build.sbt, src/main/scala/eventstore/Event.scala, src/main/scala/eventstore/cluster/ClusterInfo.scala, src/main/scala/eventstore/cluster/ClusterProtocol.scala, src/main/scala/eventstore/tcp/EventStoreProtoFormats.scala, src/test/scala/eventstore/ResolvedEventSpec.scala, src/test/scala/eventstore/TestConnection.scala, src/test/scala/eventstore/cluster/ClusterDiscovererActorSpec.scala, src/test/scala/eventstore/cluster/ClusterInfoSpec.scala, src/test/scala/eventstore/cluster/ClusterProtocolSpec.scala, src/test/scala/eventstore/cluster/DateFormatSpec.scala
- remove usage of joda libraries and replace
with java.time.*
- using `ZoneId.systemDefault` for `created` field
on `EventRecord`. This is same behavior as joda
`new DateTime(x.getCreatedEpoch)`.
- Note: This is a breaking change as `created`
on `Event` is changed from joda to java.time.
=> date: replace joda with java.time

build.sbt, client/src/main/scala/eventstore/akka/tcp/BidiLogging.scala, client/src/test/scala/eventstore/akka/EventStoreExtensionSpec.scala, client/src/test/scala/eventstore/akka/tcp/BidiLoggingSpec.scala, client/src/test/scala/eventstore/akka/testutil/TestLogger.scala, client/src/test/scala/eventstore/j/EsConnectionITest.scala, core/src/test/scala/eventstore/operations/RetryableOperationSpec.scala, project/Dependencies.scala, project/plugins.sbt
- remove dependency on mockito from projects
and adjust `RetryableOperationSpec` and
`BidiLoggingSpec`.
- enable `fatal-warnings` for `scalac`.
- remove deprecated usage of `publisher` methods in
`j/EsConnectionITest`
- bump dependencies for sbt plugins and libraries.
- add `TestLogger` that replaces mocking of
`LoggingAdapter`. It is by no means complete and
principled, but it solves the logging need of Akka.
- fix ask timeout issue in `EventstoreExtensionSpec`.
=> misc: rm mockito / deps / fatal warnings

.travis.yml, build.sbt, client/src/main/scala/eventstore/akka/streams/SourceStageLogic.scala, client/src/main/scala/eventstore/akka/tcp/Client.scala, client/src/main/scala/eventstore/akka/tcp/ConnectionActor.scala, client/src/test/scala/eventstore/akka/ProjectionsClientITest.scala, client/src/test/scala/eventstore/akka/TestConnection.scala, client/src/test/scala/eventstore/akka/tcp/ConnectionActorSpec.scala, client/src/test/scala/eventstore/j/EsConnectionSpec.scala, core/src/main/scala-2.12/eventstore/ScalaCompat.scala, core/src/main/scala-2.13/eventstore/ScalaCompat.scala, core/src/main/scala/eventstore/util/OneToMany.scala, project/plugins.sbt, version.sbt
- add scala 2.13 support.
- fix value-discard issues in `SourceStageLogic`, `Client`
and `ConnectionActor`.
- fix tests in `ProjectionsClientITest` wrt. `should beSome(X)`
and `X` is a case object to be `shouldEqual Some(X)` as
Scala 2.13 fails with a `type mismatch` error.
- add `ScalaCompat` object in unmanaged sources in
core project in order to be able to cross compile.
- change `TestConnection` to use `ScalaCompat` in order to get
Scala 2.12 and 2.13 working with minimal changes, `LazyList`
replaces `Stream`.
- fix shadow warnings and unused variables in `ConnectionActorSpec`
and `ProjectionsClientITest`.
- change `OneToMany` to use `Iterable` and `IterableOnce` and
use `import eventstore.ScalaCompat._` in order to have cross
builds working.
- change build.sbt and version.sbt to use …
=> all: scala 2.13 support + sbt syntax

build.sbt, client/src/main/scala/eventstore/akka/EsConnection.scala, client/src/main/scala/eventstore/akka/SubscriptionActor.scala, client/src/main/scala/eventstore/akka/TransactionActor.scala, client/src/main/scala/eventstore/akka/cluster/ClusterDiscovererActor.scala, client/src/main/scala/eventstore/akka/streams/SourceStageLogic.scala, client/src/main/scala/eventstore/akka/tcp/ConnectionActor.scala, client/src/main/scala/eventstore/akka/tcp/EventStoreFlow.scala, client/src/main/scala/eventstore/package.scala, client/src/main/scala/eventstore/tcp/package.scala, client/src/test/scala/eventstore/akka/EsConnectionSpec.scala, client/src/test/scala/eventstore/akka/HeavyWrite.scala, client/src/test/scala/eventstore/akka/tcp/ConnectionActorSpec.scala, client/src/test/scala/eventstore/akka/testutil/TestLogger.scala, client/src/test/scala/eventstore/j/EsConnectionSpec.scala, core/src/main/scala-2.13/eventstore/ScalaCompat.scala, core/src/main/scala/eventstore/SystemEventType.scala, core/src/test/scala/eventstore/EventStreamSpec.scala, core/src/test/scala/eventstore/PositionSpec.scala, core/src/test/scala/eventstore/operations/SimpleOperationSpec.scala, core/src/test/scala/eventstore/operations/SubscriptionOperationSpec.scala, examples/src/main/scala/eventstore/akka/examples/APIsExample.scala, examples/src/main/scala/eventstore/akka/examples/CountAll.scala, examples/src/main/scala/eventstore/akka/examples/CountStream.scala, examples/src/main/scala/eventstore/akka/examples/EventStoreExtensionExample.scala, examples/src/main/scala/eventstore/akka/examples/MessagesPerSecond.scala, examples/src/main/scala/eventstore/akka/examples/PersistentSubscriptionExample.scala, project/plugins.sbt
- remove our common `scalacOptions` additions that
now come via tpolecat plugin.
- remove unused `ExecutionContext` from `EsConnection.apply`.
- adjust code and tests to get things to compile.
=> all: add tpolecat plugin for recommended scalac options

client/src/main/scala/eventstore/CoreCompat.scala, client/src/main/scala/eventstore/cluster/package.scala, client/src/main/scala/eventstore/package.scala, client/src/main/scala/eventstore/tcp/package.scala
- add `CoreCompat` trait with objects with apply/unapply
for types in core that require settings that are obtained
by way of side-effects.
- make deprecation messages constant values and remove explicit
names as scalac itself provides that.
=> client: clean up eventstore package object

client/src/main/scala/eventstore/akka/ProjectionsClient.scala, client/src/main/scala/eventstore/akka/Settings.scala, client/src/main/scala/eventstore/akka/Tls.scala, client/src/main/scala/eventstore/akka/cluster/ClusterInfoOf.scala, client/src/main/scala/eventstore/akka/tcp/ConnectionActor.scala, client/src/test/resources/es20-tls.conf, core/src/main/resources/reference.conf, project/Dependencies.scala
- akka http 10.2.0 requires that you provide your own `SSLContext`
via `ConnectionContext.https` and has deprecated usage of
`AkkaSSLConfig`.
- move `Tls` object to `akka.eventstore` as it is used by http
now as well.
- move `ssl-config` under eventstore config instead of relying
on akka.
=> tls: improve TLS support

.docker/esdb-cluster.sh, .docker/esdb-cluster.yml, .docker/esdb-single.sh, .docker/esdb-single.yml, .docker/legacy-cluster.sh, .docker/legacy-cluster.yml, .docker/legacy-single.sh, .docker/legacy-single.yml, .github/workflows/ci.yml, .gitignore, .travis.yml, build.sbt, client/src/main/scala/eventstore/cluster/package.scala, client/src/main/scala/eventstore/package.scala, client/src/main/scala/eventstore/tcp/package.scala, client/src/test/scala/eventstore/akka/SoftDeleteStreamITest.scala, core/src/main/scala/eventstore/core/cluster/NodeState.scala, core/src/test/scala/eventstore/core/cluster/NodeStateSpec.scala, project/Dependencies.scala
- add support for node state `DiscoverLeader` and `ResigningLeader`.
- adjust tests for soft delete scenarios that
are not supported in esdb 21.10.0.
- upgrade various dependencies.
- adjust travis file for esdb updates
- fix compiler warning about deprecated usage
wrt. since not being stable identifier.
NOTE: all tests have been run locally as travis is no more.
=> misc: support for esdb 21.10.x

client/src/main/scala/eventstore/akka/cluster/ClusterDiscovererActor.scala
When using the cluster gossip seed configuration to connect with an Eventstore that's using TLS, we have something like this in gossip's endpoint response:
> {
...
"internalTcpIp": "eventstore-01.hostname.com",
"internalTcpPort": 0,
"internalSecureTcpPort": 1112,
"externalTcpIp": "eventstore-01.hostname.com",
"externalTcpPort": 0,
"externalSecureTcpPort": 1113,
"httpEndPointIp": "eventstore-01.hostname.com",
"httpEndPointPort": 2113,
...
}
Note that externalTcpPort is equal 0 in this case.
This PR is just a simple fix that, if not acceptable, would give some path to the real fix.
Please consider this issue, because I noticed that it has already been brought to your attention before.
Kind regards
Miguel
=> TLS support for connections made from cluster discovery funcionality
